### ISSUE TITLE
Code urls not working for projects outside of github.com/cdcgov

### ISSUE THREAD

**Issue by leebrian** [CDCgov/opencdc#31]
@mlamtamri found the following bug after adding info on Epi Info’s project... (#29)

“Hi Brian, The Epi info repository link is broken. Epi info products have their own repository in GitHub. They don’t exist under https://github.com/CDCgov<https://github.com/CDCgov/SDP-Vocabulary-Service>. Any suggestion on how to fix this issue?”

**Comment by drewry** [comment]
This is because of this in the layout:

`<a href="https://github.com/CDCgov/{{ repo.url }}" target="_blank">`

One suggestion would be to add a `org: MY_ORG` field into the yml and if passed it triggers a conditional to use that org instead of the default CDCgov.

The reason for capturing the org as there’s a feature for being able to search tags within a set of repos and the org field is required for that.

**Comment by leebrian** [comment]
Yep. I think I’m going to refactor to just use a full url. This would be easier for users, I think, and also allow for more flexibility in case orgs have projects with different urls (eg, blockchain has a project in github/CDCgov and github/informaticslab or something). I’ll update when near a device with a decent dev environment.

**Comment by leebrian** [comment]
Fixed in [v1.0.3](https://github.com/CDCgov/opencdc/releases/tag/v1.0.3)

Now urls for code items can go anywhere, like cool orgs like github/Epi-Info.
